### ISSUE TITLE
斯坦福机器学习笔记

### ISSUE THREAD

**Issue by ldhai** [yoyoyohamapi/mit-ml#1]
你好。请问可以提供笔记的pdf版本吗？我想下载下来观看，但是gitbook上没有pdf版本。

**Comment by yoyoyohamapi** [comment]
@ldhai 有空我转一下

**Comment by yoyoyohamapi** [comment]
@lylwh 翻墙就可以看见了

**Comment by JustinFincher** [comment]
@yoyoyohamapi 你好，mathjax 的 cdn 关闭了，导致网页公式不能显示，请问可以提供一个引用本地 js 的更新嘛？
详见：https://www.mathjax.org/cdn-shutting-down/

**Comment by yoyoyohamapi** [comment]
@JustinFincher 已更新 mathjax 的 CDN

**Comment by gongyucheng** [comment]
@yoyoyohamapi gitbook翻墙也打不开啊

**Comment by yoyoyohamapi** [comment]
@gongyucheng https://yoyoyohamapi.gitbooks.io/mit-ml/content/
