### ISSUE TITLE
数学公式问题

### ISSUE THREAD

**Issue by baozouai** [yoyoyohamapi/mit-ml#4]
你好，首先非常感谢您的笔记，感觉获益匪浅，特别是书中与python代码的结合

不过我自己有个问题，就是我在用gitbook编辑数学公式的时候，显示的是这样的

如下：
![image](https://user-images.githubusercontent.com/33510001/35467100-b4d22e7c-0345-11e8-929c-19885c12559a.png)
可是当我publish成功后去阅读的时候，公式又变成了这样子：

![image](https://user-images.githubusercontent.com/33510001/35467121-e1352ae6-0345-11e8-987a-681b0fa609b3.png)
我非常苦难，请问您知道如何解决这问题吗
对了，我用的是gitbook的网页版的

**Comment by yoyoyohamapi** [comment]
@baozouPy book.json 的 mathjax 插件换成 mathjax-update-cdn 吧，mathjax 插件里面的 cdn 已经过期了

**Comment by baozouai** [comment]
网页版有book.json吗，我不是用客户端写的

**Comment by yoyoyohamapi** [comment]
@baozouPy 有，也可以声明插件的，gitbook 服务器会帮你构建

**Comment by baozouai** [comment]
关键我自己不知道那个book.json在哪里。。。真不好意思，请问您能跟我说一下吗

**Comment by yoyoyohamapi** [comment]
@baozouPy 编辑页面左上角，有个 files

**Comment by baozouai** [comment]
点击files后，我没看到book.json，还是要自己建立?我只看到有一个gitignore，不知道这个是不是

![image](https://user-images.githubusercontent.com/33510001/35467816-83bd1cb2-034e-11e8-87ad-3ca039a02222.png)

**Comment by yoyoyohamapi** [comment]
@baozouPy 自已手动建立，你可以先学下 gitbook 基础教程，比如怎么安装插件之类的

**Comment by baozouai** [comment]
好的，感激不尽！！
