### ISSUE TITLE
神经网络前馈计算的疑问

### ISSUE THREAD

**Issue by clpl** [yoyoyohamapi/mit-ml#8]
在神经网络代码中前馈函数fp(Thetas, X)中

有一项是a[l] = np.concatenate((np.ones((1, a[l].shape[1])), a[l]))，注释是“添加偏置”

我对这一个操作有疑问，神经网络的每一层前馈不应该是WX + B吗？
应该有一个加操作，为什么这里没有体现？

**Comment by yoyoyohamapi** [comment]
@clpl 感谢反馈，最近被工作压得透不过气，空了我看看。Thx.

**Comment by clpl** [comment]
辛苦了
